# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a41f958818b1d2c7739054695f8f7093bbace3a1cb4913941ceaf3307a346616a49804b02f080d14a9745aa20c7b674c393e9909b65c2594bb3276aecba971e

test:
  secret_key_base: a1eb9244ba8ecdfa05778ab7abac39b94ab6a48c13ad6b6cc537c607aab0e092f16e0ba68cdfea9f8230c6f1adf4b3ae96d6067667a061ed79332475670e72e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
